{
 "title": "Core",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": "label_values(minerator_core_clock_multiplier, device)"
   },
   {
    "name": "core",
    "label": "core",
    "query": "label_values(minerator_core_clock_multiplier, core)"
   }
  ]
 },
 "panels": [
  { "title": "Core Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clock Multiplier",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\", core=\"$core\"}"
    }
   ]
  },
  {
   "title": "Clock Multiplier Health Overtime",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier_health{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Last Minute Hashrate Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Accepted"
    },
    {
     "expr": "minerator_core_hashrate_submitted_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "minerator_core_hashrate_submitted_per_min{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_accepted_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Rejected"
    },
    {
     "expr": "minerator_core_hashrate_valid_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "minerator_core_hashrate_found_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Found"
    },
    {
     "expr": "minerator_core_hashrate_found_per_min{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_valid_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Total Hashrate Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Accepted"
    },
    {
     "expr": "minerator_core_hashrate_submitted{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "minerator_core_hashrate_submitted{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_accepted{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Rejected"
    },
    {
     "expr": "minerator_core_hashrate_valid{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "minerator_core_hashrate_found{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Found"
    },
    {
     "expr": "minerator_core_hashrate_found{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_valid{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Total Rejected Shares",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 5 },
   "targets": [
    {
     "expr": "((minerator_core_hashrate_submitted{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_accepted{device=\"$device\", core=\"$core\"})/minerator_core_hashrate_submitted{device=\"$device\", core=\"$core\"})*100"
    }
   ]
  },
  {
   "title": "Total Hardware Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "((minerator_core_hashrate_found{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_valid{device=\"$device\", core=\"$core\"})/minerator_core_hashrate_found{device=\"$device\", core=\"$core\"})*100"
    }
   ]
  },
  {
   "title": "Total Nonces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_core_total_nonces{device=\"$device\", core=\"$core\"}"
    }
   ]
  },
  {
   "title": "Bad Nonces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_core_bad_nonces{device=\"$device\", core=\"$core\"}"
    }
   ]
  },
  { "title": "Core Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted_per_min{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Last Minute"
    },
    {
     "expr": "avg_over_time(minerator_core_hashrate_accepted_per_min{device=\"$device\", core=\"$core\"}[15m])",
     "legendFormat": "15 minute average"
    },
    {
     "expr": "minerator_core_hashrate_accepted{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Total Average"
    }
   ]
  },
  {
   "title": "Clock Multiplier + Hardware Errors",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\", core=\"$core\"}",
     "legendFormat": "Clock Multiplier"
    },
    {
     "expr": "((minerator_core_hashrate_found{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_valid{device=\"$device\", core=\"$core\"})/minerator_core_hashrate_found{device=\"$device\", core=\"$core\"})*100",
     "legendFormat": "Hardware Errors"
    }
   ]
  },
  {
   "title": "Rejected Shares % for Last Minute",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((minerator_core_hashrate_submitted_per_min{device=\"$device\", core=\"$core\"}-minerator_core_hashrate_accepted_per_min{device=\"$device\", core=\"$core\"})/minerator_core_hashrate_submitted_per_min{device=\"$device\", core=\"$core\"})*100",
     "legendFormat": "Rejected Shares %"
    }
   ]
  }
 ]
}