{
 "title": "Device",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(minerator_core_clock_multiplier, device)"
   },
   {
    "name": "sysmon",
    "query": "label_values(minerator_sysmon_health, sysmon)"
   },
   {
    "name": "phase",
    "query": "label_values(minerator_phase_temp, phase)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Quick Links", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Input Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_input_power{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Clock Multiplier",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Total Accepted Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "MHs",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Accepted Hashrate/Clock Multiplier",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted{device=\"$device\"}",
     "legendFormat": "Hashrate"
    },
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\"}",
     "legendFormat": "Multiplier"
    }
   ]
  },
  {
   "title": "VRCTRL Temp",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_vrctrl_temp{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "VCCINT",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "expr": "minerator_vccint{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "MH/Watt",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(minerator_core_hashrate_valid{device=\"$device\"}) without (core)/minerator_input_power{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Hardware Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "((minerator_core_hashrate_found{device=\"$device\"}-minerator_core_hashrate_valid{device=\"$device\"})/minerator_core_hashrate_found{device=\"$device\"})*100"
    }
   ]
  },
  {
   "title": "Rejected Shares",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "((minerator_core_hashrate_submitted{device=\"$device\"}-minerator_core_hashrate_accepted{device=\"$device\"})/minerator_core_hashrate_submitted{device=\"$device\"})*100"
    }
   ]
  },
  {
   "title": "Hashrates Last Minute",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted_per_min{device=\"$device\"}",
     "legendFormat": "Accepted"
    },
    {
     "expr": "minerator_core_hashrate_submitted_per_min{device=\"$device\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "minerator_core_hashrate_valid_per_min{device=\"$device\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "minerator_core_hashrate_found_per_min{device=\"$device\"}",
     "legendFormat": "Found"
    }
   ]
  },
  {
   "title": "Health over time",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "minerator_aux12_current_health{device=\"$device\"}",
     "legendFormat": "AUX12V Current"
    },
    {
     "expr": "minerator_aux12v_health{device=\"$device\"}",
     "legendFormat": "AUX12V"
    },
    {
     "expr": "minerator_pex12v_current_health{device=\"$device\"}",
     "legendFormat": "PEX12V  Current"
    },
    {
     "expr": "minerator_pex12v_health{device=\"$device\"}",
     "legendFormat": "PEX12V"
    },
    {
     "expr": "minerator_vrctrl_temp_health{device=\"$device\"}",
     "legendFormat": "VRCTRL Temp"
    },
    {
     "expr": "minerator_core_clock_multiplier_health{device=\"$device\"}",
     "legendFormat": "Clock Multi"
    },
    {
     "expr": "minerator_input_power_health{device=\"$device\"}",
     "legendFormat": "Input Power"
    },
    {
     "expr": "minerator_vccint_current_health{device=\"$device\"}",
     "legendFormat": "VCCINT Current"
    },
    {
     "expr": "minerator_phase_temp_health{device=\"$device\", phase=\"0\"}",
     "legendFormat": "Phase 0 Temp"
    },
    {
     "expr": "minerator_phase_temp_health{device=\"$device\", phase=\"1\"}",
     "legendFormat": "Phase 1 Temp"
    },
    {
     "expr": "minerator_sysmon_health{device=\"$device\", sysmon=\"0\"}",
     "legendFormat": "Sysmon 0 Temp"
    },
    {
     "expr": "minerator_sysmon_health{device=\"$device\", sysmon=\"1\"}",
     "legendFormat": "Sysmon 1 Temp"
    },
    {
     "expr": "minerator_sysmon_health{device=\"$device\", sysmon=\"2\"}",
     "legendFormat": "Sysmon 2 Temp"
    }
   ]
  },
  {
   "title": "Sysmon $sysmon",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "repeat": "sysmon",
   "targets": [
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Temp (C)"
    },
    {
     "expr": "minerator_sysmon_vccbram{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCBRAM (V)"
    },
    {
     "expr": "minerator_sysmon_vccint{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCINT (V)"
    },
    {
     "expr": "minerator_sysmon_vccaux{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCAUX (V)"
    }
   ]
  },
  {
   "title": "Phase $phase",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 22 },
   "repeat": "phase",
   "targets": [
    {
     "expr": "minerator_phase_temp{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "minerator_phase_vout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "VOUT "
    },
    {
     "expr": "minerator_phase_iout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "IOUT "
    },
    { "legendFormat": "{{ phase }} | phase" }
   ]
  },
  {
   "title": "Health Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "minerator_input_power_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | Input Power"
    },
    {
     "expr": "minerator_input_power{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | Input Power"
    },
    {
     "expr": "minerator_aux12v_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | AUX12V"
    },
    {
     "expr": "minerator_aux12v{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | AUX12V"
    },
    {
     "expr": "minerator_aux12_current_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | AUX12V Current"
    },
    {
     "expr": "minerator_aux12_current{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | AUX12V Current"
    },
    {
     "expr": "minerator_pex12v_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | PEX12V"
    },
    {
     "expr": "minerator_pex12v{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | PEX12V"
    },
    {
     "expr": "minerator_pex12v_current_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | PEX12V Current"
    },
    {
     "expr": "minerator_pex12v_current{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | PEX12V Current"
    },
    {
     "expr": "minerator_vccint_current_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | VCCINT Current"
    },
    {
     "expr": "minerator_vccint_current{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | VCCINT Current"
    },
    {
     "expr": "minerator_vrctrl_temp_health{device=\"$device\"}",
     "legendFormat": "{{ device }} | Health | VRCTRL Temp"
    },
    {
     "expr": "minerator_vrctrl_temp{device=\"$device\"}",
     "legendFormat": "{{ device }} | Value | VRCTRL Temp"
    }
   ]
  },
  {
   "title": "Temperature Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 22 },
   "targets": [
    {
     "expr": "minerator_fpga_temp{device=\"$device\"}",
     "legendFormat": "FPGA"
    },
    {
     "expr": "minerator_vrctrl_temp{device=\"$device\"}",
     "legendFormat": "VRCTRL"
    },
    {
     "expr": "minerator_phase_temp{device=\"$device\"}",
     "legendFormat": "Phase {{ phase }}"
    },
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\"}",
     "legendFormat": "Sysmon {{ sysmon }}"
    }
   ]
  },
  {
   "title": "Sysmon $sysmon",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Temp (C)"
    },
    {
     "expr": "minerator_sysmon_vccbram{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCBRAM (V)"
    },
    {
     "expr": "minerator_sysmon_vccint{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCINT (V)"
    },
    {
     "expr": "minerator_sysmon_vccaux{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCAUX (V)"
    }
   ]
  },
  {
   "title": "Phase $phase",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "targets": [
    {
     "expr": "minerator_phase_temp{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "minerator_phase_vout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "VOUT "
    },
    {
     "expr": "minerator_phase_iout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "IOUT "
    },
    { "legendFormat": "{{ phase }} | phase" }
   ]
  },
  {
   "title": "Voltages",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 10, "y": 31 },
   "targets": [
    {
     "expr": "minerator_vccint{device=\"$device\"}",
     "legendFormat": "VCCINT"
    },
    {
     "expr": "minerator_aux12v{device=\"$device\"}",
     "legendFormat": "AUX12V"
    },
    {
     "expr": "minerator_aux3v3{device=\"$device\"}",
     "legendFormat": "AUX3V3"
    },
    {
     "expr": "minerator_pex12v{device=\"$device\"}",
     "legendFormat": "PEX12V"
    },
    {
     "expr": "minerator_pex3v3{device=\"$device\"}",
     "legendFormat": "PEX3V3"
    },
    {}
   ]
  },
  {
   "title": "Amps",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 13, "y": 31 },
   "targets": [
    {
     "expr": "minerator_vccint_current{device=\"$device\"}",
     "legendFormat": "VCCINT"
    },
    {
     "expr": "minerator_aux12_current{device=\"$device\"}",
     "legendFormat": "AUX12V"
    },
    {
     "expr": "minerator_pex12v_current{device=\"$device\"}",
     "legendFormat": "PEX12V"
    },
    {
     "expr": "minerator_pex3v3_current{device=\"$device\"}",
     "legendFormat": "PEX3V3"
    },
    {}
   ]
  },
  {
   "title": "Sysmon $sysmon",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Temp (C)"
    },
    {
     "expr": "minerator_sysmon_vccbram{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCBRAM (V)"
    },
    {
     "expr": "minerator_sysmon_vccint{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCINT (V)"
    },
    {
     "expr": "minerator_sysmon_vccaux{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCAUX (V)"
    }
   ]
  },
  { "title": "Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Efficiency (Minute Average)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "MH/Watt" }
   ],
   "targets": [
    {
     "expr": "max(minerator_core_hashrate_valid_per_min{device=\"$device\"}) without (core)/minerator_input_power{device=\"$device\"}",
     "legendFormat": "Efficiency"
    },
    {
     "expr": "minerator_core_hashrate_accepted_per_min{device=\"$device\"}",
     "legendFormat": "Hashrate"
    }
   ]
  },
  {
   "title": "Efficiency (Total)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "MH/Watt" }
   ],
   "targets": [
    {
     "expr": "max(minerator_core_hashrate_valid{device=\"$device\"}) without (core)/minerator_input_power{device=\"$device\"}",
     "legendFormat": "Efficiency"
    },
    {
     "expr": "minerator_core_hashrate_valid{device=\"$device\"}",
     "legendFormat": "Hashrate"
    }
   ]
  },
  {
   "title": "Multiplier vs Hardware Errors",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short", "label": "Multiplier" }
   ],
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\"}",
     "legendFormat": "Clock Multi"
    },
    {
     "expr": "((minerator_core_hashrate_found_per_min{device=\"$device\"}-minerator_core_hashrate_valid_per_min{device=\"$device\"})/minerator_core_hashrate_found_per_min{device=\"$device\"})*100",
     "legendFormat": "Hardware Errors"
    }
   ]
  },
  {
   "title": "Multipler vs Input Power",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none", "label": "Multiplier" }
   ],
   "targets": [
    {
     "expr": "minerator_core_clock_multiplier{device=\"$device\"}",
     "legendFormat": "Clock Multi"
    },
    {
     "expr": "minerator_input_power{device=\"$device\"}",
     "legendFormat": "Power"
    }
   ]
  }
 ]
}