{
 "title": "Minerator Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Quick Links", "type": "dashlist", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "Active Pool",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, minerator_hashrate_accepted)",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Worksource Hashrate Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "targets": [
    { "expr": "minerator_hashrate_accepted{}", "legendFormat": "{{ pool }} | Total (MH) |" },
    { "expr": "minerator_fee_accepted{}", "legendFormat": "{{ name }} | Total (MH) |" },
    {
     "expr": "minerator_hashrate_accepted_per_min{}",
     "legendFormat": "{{ pool }} | Last Minute (MH) |"
    },
    {
     "expr": "minerator_fee_accepted_per_min{}",
     "legendFormat": "{{ name }} | Last Minute (MH) |"
    },
    {
     "expr": "((minerator_hashrate_submitted{}-minerator_hashrate_accepted{})/minerator_hashrate_submitted{})*100",
     "legendFormat": "{{ pool }} | Rejected Shares (%)|"
    },
    {
     "expr": "((minerator_fee_submitted{}-minerator_fee_accepted{})/minerator_fee_submitted{})*100",
     "legendFormat": "{{ name }} | Rejected Shares (%)|"
    }
   ]
  },
  {
   "title": "Device Hashrate Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "minerator_core_hashrate_accepted{}",
     "legendFormat": "{{ device }}| Total Hashrate"
    },
    {
     "expr": "minerator_core_hashrate_accepted_per_min{}",
     "legendFormat": "{{ device }}| Last Minute Hashrate"
    },
    {
     "expr": "minerator_core_clock_multiplier{}",
     "legendFormat": "{{ device }}| Clock Multiplier"
    },
    {
     "expr": "minerator_core_clock_multiplier_health{}",
     "legendFormat": "{{ device }}| Clock Multiplier Health"
    },
    {
     "expr": "max(minerator_core_hashrate_valid{}) without (core)/minerator_input_power{}",
     "legendFormat": "{{ device }}| MH/Watt"
    }
   ]
  },
  {
   "title": "Total Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 4 },
   "format": "MHs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(minerator_hashrate_accepted{pool=~\".*\"})"
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(minerator_vccint{device=~\".*\"}) by (device))"
    }
   ]
  },
  {
   "title": "Temperature Health Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "minerator_vrctrl_temp_health{}", "legendFormat": "{{ device }} | VRCTRL" },
    {
     "expr": "minerator_sysmon_health{sysmon=\"0\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_sysmon_health{sysmon=\"1\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_sysmon_health{sysmon=\"2\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_phase_temp_health{phase=\"0\"}",
     "legendFormat": "{{ device }} | Phase {{ phase }}"
    },
    {
     "expr": "minerator_phase_temp_health{phase=\"1\"}",
     "legendFormat": "{{ device }} | Phase {{ phase }}"
    }
   ]
  },
  {
   "title": "Temperature Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "minerator_vrctrl_temp{}", "legendFormat": "{{ device }} | VRCTRL" },
    {
     "expr": "minerator_sysmon_temperature{sysmon=\"0\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_sysmon_temperature{sysmon=\"1\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_sysmon_temperature{sysmon=\"2\"}",
     "legendFormat": "{{device}} | Sysmon {{ sysmon }}"
    },
    {
     "expr": "minerator_phase_temp{phase=\"0\"}",
     "legendFormat": "{{ device }} | Phase {{ phase }}"
    },
    {
     "expr": "minerator_phase_temp{phase=\"1\"}",
     "legendFormat": "{{ device }} | Phase {{ phase }}"
    }
   ]
  },
  {
   "title": "Active Worksources",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "minerator_hashrate_accepted_per_min{}",
     "legendFormat": "{{ pool }}"
    },
    {
     "expr": "minerator_fee_accepted_per_min{}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Device Hashrates (15 minute average)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "MHs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(minerator_core_hashrate_accepted_per_min{}[15m])",
     "legendFormat": "Device {{ device }}"
    }
   ]
  }
 ]
}