{
 "title": "Phase",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": "label_values(minerator_core_clock_multiplier, device)"
   },
   {
    "name": "phase",
    "label": "phase",
    "query": "label_values(minerator_phase_temp, phase)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Health Overtime",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "minerator_phase_temp_health{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Temperature Overview",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "minerator_phase_temp{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "{{ $phase }} | Temperature  "
    },
    {
     "expr": "minerator_phase_temp_health{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "{{ $phase }} | Health "
    },
    {
     "expr": "max_over_time(minerator_phase_temp{device=\"$device\", phase=\"$phase\"}[$__range])",
     "legendFormat": "{{ $phase }} | Max"
    },
    {
     "expr": "min_over_time(minerator_phase_temp{device=\"$device\", phase=\"$phase\"}[$__range])",
     "legendFormat": "{{ $phase }} |  Min"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "minerator_phase_temp{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Power Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "minerator_phase_vout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "VOUT (Volts)"
    },
    {
     "expr": "minerator_phase_iout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "IOUT (Amps)"
    }
   ]
  },
  {
   "title": "VOUT",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "minerator_phase_vout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "VOUT"
    }
   ]
  },
  {
   "title": "IOUT",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "minerator_phase_iout{device=\"$device\", phase=\"$phase\"}",
     "legendFormat": "IOUT"
    }
   ]
  }
 ]
}