{
 "title": "Sysmon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "label_values(minerator_core_clock_multiplier, device)"
   },
   {
    "name": "sysmon",
    "query": "label_values(minerator_sysmon_health, sysmon)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health Overtime",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "minerator_sysmon_health{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Temperature Status",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "{{ $sysmon }} | Temperature | Sysmon"
    },
    {
     "expr": "minerator_sysmon_health{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "{{ $sysmon }} | Health | Sysmon"
    },
    {
     "expr": "max_over_time(minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}[$__range])",
     "legendFormat": "{{ $sysmon }} | Max | Sysmon "
    },
    {
     "expr": "min_over_time(minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}[$__range])",
     "legendFormat": "{{ $sysmon }} | Min | Sysmon "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "minerator_sysmon_temperature{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Sysmon {{ sysmon }}"
    }
   ]
  },
  {
   "title": "Voltage Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "minerator_sysmon_vccint{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCINT"
    },
    {
     "expr": "minerator_sysmon_vccaux{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCAUX"
    },
    {
     "expr": "minerator_sysmon_vccbram{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "VCCBRAM"
    }
   ]
  },
  {
   "title": "VCCINT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "minerator_sysmon_vccint{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Sysmon {{ sysmon }}"
    }
   ]
  },
  {
   "title": "VCCBRAM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "minerator_sysmon_vccbram{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Sysmon {{ sysmon }}"
    }
   ]
  },
  {
   "title": "VCCAUX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "minerator_sysmon_vccaux{device=\"$device\", sysmon=\"$sysmon\"}",
     "legendFormat": "Sysmon {{ sysmon }}"
    }
   ]
  },
  { "title": "Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}